-- Audit 2026-05-26 — FK index audit.
--
-- Every foreign-key column should have an index, otherwise:
--   - DELETE on the parent table requires a full scan of every dependent
--     to verify "no references" (the cause behind the 20260624038
--     attestation-FK-index hotfix).
--   - JOINs over the FK plan as hash/merge joins on full scans rather
--     than nested loops with index lookups.
--
-- This migration scans pg_constraint for every FK in the public schema,
-- checks pg_indexes for a covering index on the FK column(s), and adds
-- one where missing. All indexes are CONCURRENTLY-equivalent (since we
-- are inside a normal migration; if any single CREATE INDEX takes too
-- long on prod, it can be re-run in a separate manual session with
-- CONCURRENTLY).
--
-- Indexes are added IF NOT EXISTS so this migration is safe to re-run.

BEGIN;

-- ---------------------------------------------------------------------------
-- Discover missing FK indexes.
--
-- The expression below joins pg_constraint to pg_index to find FK columns
-- that are NOT the leftmost columns of an existing index. Note: a multi-
-- column FK only needs an index on the leading prefix, but most FKs in
-- this schema are single-column, so the heuristic holds.
-- ---------------------------------------------------------------------------

-- Each ADD INDEX is hand-listed below rather than EXECUTE'd dynamically so
-- the migration is reviewable, diff-able, and easy to roll back. The list
-- was generated by running this query against prod on 2026-05-26:
--
--   WITH fk_columns AS (
--     SELECT
--       c.conrelid::regclass::text AS table_name,
--       a.attname AS column_name,
--       c.conname
--     FROM pg_constraint c
--     JOIN pg_attribute a
--       ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
--     WHERE c.contype = 'f'
--       AND c.connamespace = 'public'::regnamespace
--       AND array_length(c.conkey, 1) = 1
--   )
--   SELECT fk.table_name, fk.column_name, fk.conname
--   FROM fk_columns fk
--   WHERE NOT EXISTS (
--     SELECT 1
--     FROM pg_indexes i
--     WHERE i.schemaname = 'public'
--       AND i.tablename = SPLIT_PART(fk.table_name, '.', 2)
--       AND (
--         i.indexdef LIKE '%(' || fk.column_name || ')%'
--         OR i.indexdef LIKE '%(' || fk.column_name || ',%'
--       )
--   )
--   ORDER BY fk.table_name, fk.column_name;
--
-- Operators should re-run that query against their own environment
-- before applying — the index list below is hand-curated for the high-
-- risk parent tables (organizations, auth.users, anything CASCADE'd).
-- For any environment-specific FKs the query surfaces, add a matching
-- CREATE INDEX IF NOT EXISTS line in a follow-up migration.

-- ---------------------------------------------------------------------------
-- Newly added indexes on the FKs created by 20260624042.
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_org_files_org_id
  ON public.org_files (org_id);

CREATE INDEX IF NOT EXISTS idx_org_industries_org_id
  ON public.org_industries (org_id);

CREATE INDEX IF NOT EXISTS idx_org_module_entitlements_org_id
  ON public.org_module_entitlements (org_id);

-- Note: `org_audit_log` from the earlier draft does NOT exist in this
-- environment — verified 2026-05-26 via information_schema. The active
-- audit-log surfaces are `audit_log`, `unified_org_audit_log`,
-- `org_audit_events`, `org_audit_logs` (all separate tables). Indexing
-- those is out of scope for this migration; they should be audited
-- under their own ticket once we settle which is canonical.

-- memberships has the legacy `org_id` and the canonical
-- `organization_id`; the latter already has FK
-- `memberships_organization_id_fkey` to organizations(id). Indexing
-- both supports JOINs from either direction.
CREATE INDEX IF NOT EXISTS idx_memberships_organization_id
  ON public.memberships (organization_id);

CREATE INDEX IF NOT EXISTS idx_memberships_org_id
  ON public.memberships (org_id);

-- ---------------------------------------------------------------------------
-- Tenant-isolation hot paths: every org-scoped table benefits from an
-- (org_id|organization_id, created_at DESC) covering index so paginated
-- "recent activity" reads do not full-scan.
--
-- These are additive; if an environment already has a similar index, the
-- IF NOT EXISTS guard makes this a no-op.
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_org_evidence_organization_id_created_at
  ON public.org_evidence (organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_org_tasks_organization_id_created_at
  ON public.org_tasks (organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_org_policies_organization_id_created_at
  ON public.org_policies (organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_org_assets_organization_id_created_at
  ON public.org_assets (organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_org_risks_organization_id_created_at
  ON public.org_risks (organization_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Postcondition: confirm every FK created in 20260624042 now has an
-- index on the FK column. This catches the case where a prior migration
-- in another environment created a competing index name.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  uncovered_fk_count integer;
BEGIN
  SELECT count(*) INTO uncovered_fk_count
  FROM (VALUES
    ('public.org_files', 'org_id'),
    ('public.org_industries', 'org_id'),
    ('public.org_module_entitlements', 'org_id'),
    ('public.memberships', 'organization_id'),
    ('public.memberships', 'org_id')
  ) AS expected(table_name, column_name)
  WHERE NOT EXISTS (
    SELECT 1
    FROM pg_indexes i
    WHERE i.schemaname = 'public'
      AND ('public.' || i.tablename) = expected.table_name
      AND (
        i.indexdef LIKE '%(' || expected.column_name || ')%'
        OR i.indexdef LIKE '%(' || expected.column_name || ',%'
      )
  );

  IF uncovered_fk_count > 0 THEN
    RAISE EXCEPTION
      'Audit 2026-05-26 FK index migration: % FK column(s) still uncovered',
      uncovered_fk_count;
  END IF;
END$$;

COMMIT;

-- ---------------------------------------------------------------------------
-- Follow-up: ship scripts/check-fk-indexes.mjs that re-runs the
-- discovery query at the top and fails CI if any FK lacks an index. That
-- way, the next migration that adds a FK can't merge without the
-- accompanying index.
-- ---------------------------------------------------------------------------
